param(
    [Parameter(Mandatory = $true)][string]$OutputFile
)

# Generates the ApplyContextMenus procedure that FFActions.iss includes into its
# [Code] section. FFActions.iss runs this script itself at compile time, so the
# output is not committed. No module cmdlets here, see context_menu_layout.ps1.

$ErrorActionPreference = 'Stop'

. ([System.IO.Path]::Combine($PSScriptRoot, 'context_menu_layout.ps1'))

function ConvertTo-PascalString {
    param([string]$Value)

    return "'" + $Value.Replace("'", "''") + "'"
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('{ Generated by dev\build_menu_iss.ps1 from dev\context_menu.psd1. Do not edit. }')
$lines.Add('')
$lines.Add('procedure ApplyContextMenus;')
$lines.Add('begin')

$family = $null
foreach ($entry in (Get-ContextMenuEntries)) {
    if ($entry.Family -ne $family) {
        $family = $entry.Family
        $lines.Add('  BeginContextMenuFamily;')
    }

    if ($entry.StartsGroup) {
        $lines.Add('  StartContextMenuGroup;')
    }

    $arguments = @(
        (ConvertTo-PascalString ($entry.Extensions -join ','))
        (ConvertTo-PascalString $entry.VerbName)
        (ConvertTo-PascalString $entry.Label)
        (ConvertTo-PascalString $entry.Exe)
        (ConvertTo-PascalString $entry.Icon)
        $(if ($entry.AllUsers) { 'True' } else { 'False' })
    )

    $lines.Add('  if WizardIsComponentSelected({0}) then' -f (ConvertTo-PascalString $entry.Component))
    $lines.Add('    ApplyActionMenuList({0});' -f ($arguments -join ', '))
}

$lines.Add('end;')

$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutputFile, (($lines -join "`r`n") + "`r`n"), $encoding)
